# directory with MSAs
PATH_MSAS: "/data/msas-pangeblocks/msas-HLA-zoo/mafft.op1.53-ep0"

# make_prg
MAKEPRG_OUTPUT: "HLA-zoo-makeprg/output-HLA-zoo-mafft.op1.53-ep0"

# PanPA
PANPA_OUTPUT: "didelot-PanPA/output-didelot-mafft.op3-ep0"

# minigraph
MINIGRAPH_OUTPUT: "output/minigraph"