# directory with MSAs
PATH_MSAS: "msas"

# make_prg
MAKEPRG:
  PATH_OUTPUT: "output/makeprg"

# minigraph
MINIGRAPH:
  PATH_OUTPUT: "output/minigraph"

# PanPA
PANPA:
  PATH_OUTPUT: "output/PanPA"

# pangeblocks
PATH_OUTPUT: "output/pangeblocks"
OPTIMIZATION:
  OBJECTIVE_FUNCTION: "weighted" # nodes, strings, weighted
  PENALIZATION: 3 # used only with "weighted"
  MIN_LEN: 2 # used only with "weighted"
LOG_LEVEL: "INFO"